### ISSUE TITLE
How to pass value from outside to variables in expression_file?

### ISSUE THREAD

**Issue by natrys** [ivan-tkatchev/tab#3]
I have a slightly big program for which I would rather use expression file instead of inlining at shell. But I also need to pass in value of variables from outside. When program was inlined I could simply do variable expansion at shell level, but I am not sure what to do in expression file.

Fwiw, I had been (ab)using the bug that was fixed [recently](https://github.com/ivan-tkatchev/tab/commit/76b5084c0690e185eb93829c9ee474ce0a2a2be2). Before, the expression file was actually appended to inline expressions. So I could do:

``` sh
tab -f program.tab "var=$var"
```

Which doesn't work now that expression file is prepended so the variable in it is not yet in scope.

**Comment by ivan-tkatchev** [comment]
An easy solution would be to add a command-line switch to set the "prelude". (The initializing expression that is executed before all other expressions.)
Sounds good? I'll add it ASAP if there are no objections.

**Comment by natrys** [comment]
Yes it sounds good, and will be close to how I was making do before. Thanks in advance.

**Comment by ivan-tkatchev** [comment]
I just pushed a 9.1 release with a `-p` option, check it out.

**Comment by natrys** [comment]
Yup, my scripts are working again with `-p`. Thanks a lot.
