### ISSUE TITLE
gcc 12 compatibility

### ISSUE THREAD

**Issue by vcunat** [ivan-tkatchev/tab#5]
`funcs/cutgrep.h` is causing issues with gcc12 (with tab-9.1).  There's missing `#include <cstring>` and apparently some other fixes are needed, too.

**Comment by ivan-tkatchev** [comment]
Thank you for the bug report. Adding the missing include seems to have fixed it.

**Comment by vcunat** [comment]
Ah, I missed something apparently.  Thanks.  In nixpkgs as https://github.com/NixOS/nixpkgs/commit/ef5aa34f4c3a5b694c35dac51f0bfc37c486d978 since the patch wouldn't apply as-is and it's trivial.
